/**********************************/
/* Table Name: 1대1문의 첨부파일 */
/**********************************/
DROP TABLE INQUIRE_ATTACHFILE;
CREATE TABLE INQUIRE_ATTACHFILE(
		INQUIRE_ATTACHFILENO          		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		INQUIRENO                     		NUMBER(10)		 NULL ,
		INQUIRE_FNAME                 		VARCHAR2(100)		 NOT NULL,
		INQUIRE_FUPNAME               		VARCHAR2(100)		 NOT NULL,
		INQUIRE_THUMB                 		VARCHAR2(100)		 NULL ,
		INQUIRE_FSIZE                 		NUMBER(10)		 NOT NULL,
		INQUIRE_RDATE                 		DATE		 NOT NULL,
  FOREIGN KEY (INQUIRENO) REFERENCES INQUIRE (INQUIRENO)
);

COMMENT ON TABLE INQUIRE_ATTACHFILE is '1대1문의 첨부파일';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRE_ATTACHFILENO is '첨부파일 번호';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRENO is '문의 번호';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRE_FNAME is '원본 파일명';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRE_FUPNAME is '업로드 파일명';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRE_THUMB is 'Thumb 파일';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRE_FSIZE is '파일 사이즈';
COMMENT ON COLUMN INQUIRE_ATTACHFILE.INQUIRE_RDATE is '등록일';

DROP SEQUENCE INQUIRE_ATTACHFILE_seq;
CREATE SEQUENCE INQUIRE_ATTACHFILE_seq
  START WITH 1              -- 시작 번호
  INCREMENT BY 1          -- 증가값
  MAXVALUE 9999999999 -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;