/**********************************/
/* Table Name: 1대1문의 답변 */
/**********************************/
CREATE TABLE INQUIRE_REPLY(
		INQUIRE_REPLYNO               		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		INQUIRENO                     		NUMBER(10)		 NOT NULL,
		MEM_NO                        		NUMBER(10)		 NOT NULL,
		REPLY_CONTENT                 		VARCHAR2(300)		 NOT NULL,
		REPLY_PASSWD                  		VARCHAR2(20)		 NOT NULL,
		REPLY_RDATE                   		DATE		 NOT NULL,
		MANAGERNO                     		NUMBER(10)		 NULL ,
  FOREIGN KEY (INQUIRENO) REFERENCES INQUIRE (INQUIRENO),
  FOREIGN KEY (MANAGERNO) REFERENCES MANAGER (MANAGERNO)
);

COMMENT ON TABLE INQUIRE_REPLY is '1대1문의 답변';
COMMENT ON COLUMN INQUIRE_REPLY.INQUIRE_REPLYNO is '1대1문의 답변 번호';
COMMENT ON COLUMN INQUIRE_REPLY.INQUIRENO is '문의 번호';
COMMENT ON COLUMN INQUIRE_REPLY.MEM_NO is '회원 번호';
COMMENT ON COLUMN INQUIRE_REPLY.REPLY_CONTENT is '답변 내용';
COMMENT ON COLUMN INQUIRE_REPLY.REPLY_PASSWD is '패스워드';
COMMENT ON COLUMN INQUIRE_REPLY.REPLY_RDATE is '등록일';
COMMENT ON COLUMN INQUIRE_REPLY.MANAGERNO is '관리자 번호';