/**********************************/
/* Table Name: 1대1문의 */
/**********************************/
CREATE TABLE INQUIRE(
		INQUIRENO                     		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		MEM_NO                        		NUMBER(10)		 NOT NULL,
		INQUIRE_TITLE                 		VARCHAR2(100)		 NOT NULL,
		INQUIRE_CONTENT               		VARCHAR2(300)		 NOT NULL,
		INQUIRE_RNAME                 		VARCHAR2(10)		 NOT NULL,
		INQUIRE_PASSWD                		VARCHAR2(15)		 NOT NULL,
		WORD                          		VARCHAR2(300)		 NULL ,
		INQUIRE_RDATE                 		DATE		 NOT NULL,
		MEMNO                         		NUMBER(10)		 NULL ,
		INQUIRECATE                   		NUMBER(10)		 NULL ,
  FOREIGN KEY (MEMNO) REFERENCES MEM (MEMNO),
  FOREIGN KEY (INQUIRECATE) REFERENCES INQUIRECATE (INQUIRECATE)
);

COMMENT ON TABLE INQUIRE is '1대1문의';
COMMENT ON COLUMN INQUIRE.INQUIRENO is '문의 번호';
COMMENT ON COLUMN INQUIRE.MEM_NO is '회원 번호';
COMMENT ON COLUMN INQUIRE.INQUIRE_TITLE is '문의 제목';
COMMENT ON COLUMN INQUIRE.INQUIRE_CONTENT is '문의 내용';
COMMENT ON COLUMN INQUIRE.INQUIRE_RNAME is '등록자';
COMMENT ON COLUMN INQUIRE.INQUIRE_PASSWD is '패스워드';
COMMENT ON COLUMN INQUIRE.WORD is '검색어';
COMMENT ON COLUMN INQUIRE.INQUIRE_RDATE is '등록일';
COMMENT ON COLUMN INQUIRE.MEMNO is '회원번호';
COMMENT ON COLUMN INQUIRE.INQUIRECATE is '문의 카테고리 번호';