/**********************************/
/* Table Name: 관리자 */
/**********************************/
DROP TABLE MANAGER;
CREATE TABLE MANAGER(
		MANAGERNO                     		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		MANAGER_IMG                   		VARCHAR2(1000)		 NULL ,
		MANAGER_ID                    		VARCHAR2(50)		 NOT NULL,
		MANAGER_PW                    		VARCHAR2(20)		 NOT NULL,
		MANAGER_NAME                  		VARCHAR2(20)		 NOT NULL,
		MANAGER_YY                    		NUMBER(20)		 NOT NULL,
		MANAGER_MM                    		NUMBER(20)		 NOT NULL,
		MANAGER_DD                    		NUMBER(20)		 NOT NULL,
		MANAGER_TELECOM               		VARCHAR2(20)		 NOT NULL,
		MANAGER_PHONE                 		NUMBER(20)		 NOT NULL,
		MANAGER_EMAIL                 		VARCHAR2(50)		 NOT NULL,
		MANAGER_POSTCODE              		VARCHAR2(20)		 NOT NULL,
		MANAGER_ADDRESS1              		VARCHAR2(80)		 NOT NULL,
		MANAGER_ADDRESS2              		VARCHAR2(80)		 NOT NULL,
		JOINDATE                      		DATE		 NOT NULL,
		MANAGERLVNO                   		NUMBER(10)		 NOT NULL,
  FOREIGN KEY (MANAGERLVNO) REFERENCES MANAGERLV (MANAGERLVNO)
);

COMMENT ON TABLE MANAGER is '관리자';
COMMENT ON COLUMN MANAGER.MANAGERNO is '관리자 번호';
COMMENT ON COLUMN MANAGER.MANAGER_IMG is '관리자 사진';
COMMENT ON COLUMN MANAGER.MANAGER_ID is '관리자 아이디';
COMMENT ON COLUMN MANAGER.MANAGER_PW is '관리자 비밀번호';
COMMENT ON COLUMN MANAGER.MANAGER_NAME is '관리자 이름';
COMMENT ON COLUMN MANAGER.MANAGER_YY is '관리자 년';
COMMENT ON COLUMN MANAGER.MANAGER_MM is '관리자 월';
COMMENT ON COLUMN MANAGER.MANAGER_DD is '관리자 일';
COMMENT ON COLUMN MANAGER.MANAGER_TELECOM is '관리자 통신사';
COMMENT ON COLUMN MANAGER.MANAGER_PHONE is '관리자 전화번호';
COMMENT ON COLUMN MANAGER.MANAGER_EMAIL is '관리자 이메일';
COMMENT ON COLUMN MANAGER.MANAGER_POSTCODE is '관리자 우편번호';
COMMENT ON COLUMN MANAGER.MANAGER_ADDRESS1 is '관리자 주소1';
COMMENT ON COLUMN MANAGER.MANAGER_ADDRESS2 is '관리자 주소2';
COMMENT ON COLUMN MANAGER.JOINDATE is '입사일';
COMMENT ON COLUMN MANAGER.MANAGERLVNO is '관리자 등급번호';

DROP SEQUENCE MANAGER_seq;
CREATE SEQUENCE MANAGER_seq
  START WITH 1              -- 시작 번호
  INCREMENT BY 1          -- 증가값
  MAXVALUE 9999999999 -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;